image:
  registry: 000000000000.dkr.ecr.us-east-1.localhost:4566
  tag: REPLACE_ME
  pullPolicy: IfNotPresent

api:
  replicas: 1

worker:
  replicas: 1

frontend:
  replicas: 1

config:
  frontendOrigin: http://localhost:8088
  flociIp: 127.0.0.1
  storageEndpointUrl: http://floci-local:4566
  storageBucket: ciis-raw-files
  storageRegion: us-east-1
  sqsEndpointUrl: http://floci-local:4566
  sqsRegion: us-east-1
  sqsQueueName: ciis-analysis-jobs
  sqsDlqName: ciis-analysis-dlq
  workerPollSeconds: "2"
  metricsCollectionSeconds: "15"
  otelEndpoint: ""
